### ISSUE TITLE
The output file is empty

### ISSUE THREAD

**Issue by Duanmu37** [orex/supercell#60] opened 2023-04-13 10:04 UTC
Dear Orex,

 I would like to express my gratitude for Supercell, which is a great software. I have been using it recently to generate structures and the user experience has been fantastic.

However, I have recently encountered some problems that I cannot resolve, and therefore, I am hoping that you could provide assistance. The problem is as follows:

In my input file, there are four Al atoms in partly occupied sites. Directly generating the structure would result in a large number of results. Therefore, I have used the following commands step by step:

./supercell -i gamma.cif -p ":fixed" -o gamma_abg
./supercell -i gamma_abg.cif -p "Al1:fixed" -p "Al3*:fixed" -p "Al4*:fixed" -m -q -g -v 2 -n l1 -o fixed134_step1/fixed134
./supercell -i fixed134.cif -p "Al3*:fixed" -p "Al4*:fixed" -m -q -g -v 2 -n l1 -o fixed34_step2/fixed34

Everything went smoothly until here, and I obtained the cif file for Al1 and Al2 randomly distributed, and Al3 and Al4 fixed. However, when I proceeded to the next step:

./supercell -i fixed34.cif -p "Al4*:fixed" -m -q -g -v 2 -n l1 -o fixed4_step3/fixed4

There were txt files and cif files in the folder, but they were empty files, with no content. I have tried to expand the virtual machine's disk space, but the result was still the same. Did I do anything wrong? I would greatly appreciate your answer and help.

Thank you once again for providing such a great software.

Sincerely,
Duanmu.

**Comment by Duanmu37** [comment] 2023-04-13 10:46
By the way, I would like to ask, is it because the number of combinations is too large and the disk space is insufficient? Actually, I only want a few files to be output. Could you give me some advice?Thank you so much！

**Comment by orex** [comment] 2023-04-13 10:51
Dear Duanmu.

I've just check last run. `-g` options stores all energies for all structures. As the number of structures is ~7.0e+10, the file can be around 1Tb large. Do you really need it? if not, remove the option, if yes increase the disk size to a few Tb. Please also check that the filesystem you are using has such large files support. I'm running the calculation now. It should be finished in 1 hour or so. I'll check the result. As for suggestions, please check [tutorial](https://orex.github.io/supercell/external/doc/supercell_tutorial.pdf) "Sampling methods: Ca2Al2SiO7" section, where I described how to do it. Some other section can be also relevant. In general, I suggest to go through all tutorial to become familiar with `supercell`.

**Comment by Duanmu37** [comment] 2023-04-13 12:13
Dear Orex.
Thank you very much for your suggestion, after reading the tutorial carefully, I realized that I made a serious mistake. I turned on the -g option that I didn't need, which took up a lot of disk space, which caused the problem. After verification, “supercell” helped me get the required structure. Thanks again for your software and help. Sincerely, Duanmu

**Comment by orex** [comment] 2023-04-13 12:15
Awesome! Good luck with your project. Don't hesitate to contact in case of any question.

**Comment by Zul643** [comment] 2024-04-15 03:56
@orex Good Mornig, 
I am using supercell which works awsome, but recently i get some problems with the q energy calculations. though i get all combinations but the q energy file is not there. everytime i try i have this output " 24 symmetry operation found for supercell.
Symmetries operation assigned to groups.
Start Coulomb matrix (76x76) calculation.
**Coulomb matrix calculation finished.**
**Total 1 output files was deleted successfully**."
i used the -g -m and for the oxidation state i included it in the cif file.

**Comment by orex** [comment] 2024-04-16 07:14
Add `-p "Ba*:c=2" -p "Al*:c=3" -p "O*:c=-2"` to command line. Please check the tutorial and manual for detailed explanation 
https://orex.github.io/supercell/external/doc/supercell_tutorial.pdf
https://orex.github.io/supercell/external/doc/supercell_man.pdf

Additionally, It looks like that something wrong with your structure. Check it carefully once more.

**Comment by Zul643** [comment] 2024-04-16 07:28
Dear @orex Thank you so much for your response.  
I have gone through these manuals and tutorials, but I couldn't find the solution. Even though I already used the commond you provided, it gives me the error: *ERROR: Electrostatic energy cannot be calculated without charge balancing*. 
If there is no problem with the method I am using, then probably the problem is in the structure. 
Thank you for your time.

**Comment by orex** [comment] 2024-08-01 00:02
Probably this is a problem of MacOS. I have a possibility to support fully only Linux distribution. I've updated the version of MacOS for compiling the program. Please check it (https://github.com/orex/supercell/actions/runs/10189377384/artifacts/1762537089)

**Comment by orex** [comment] 2024-08-04 19:37
The issue should be solved in v2.1.1

**Closed by orex** 2024-08-04 19:37 UTC
